import streamlit as st

st.set_page_config(page_title="Immobilienbewertung", page_icon=":house_with_garden:")

st.header("Modernisierungskosten")
st.caption("Erneuerung Dacheindeckung mit Dämmung inkl. Abdeckung, Entsorgung, Bauklämpnerei: 250€ / je m² Dachfläche")
st.caption("Erneuerung Druckwasserleitung 100€ / je m² Wohnfläche")
st.caption("Erneuerung Haustürelement 6000 €")
st.caption("Erneuerung Terrassentür 2000 €")
st.caption("Erneuerung Fenster 1100 €")
st.caption("Rollladen pro lfm: 250 €")
st.caption("Erneuerung Küche 10000 €")
st.caption("Sanierung Bad 10000 €")
st.caption("Sanierung Gäste-WC 5000 €")
st.caption("Erneuerung Fußboden: 105€ / m² Wohnfläche")
st.caption("Erneuerung Innentüren: 450€")
st.caption("Erneuerung Wand-/Deckenbekleidung: 18€ / m² Wohnfläche x 3,4")
st.caption("Tapezieren (mit Anstrich): 10€ / qm")
st.caption("Verputzen: 16 € / qm")
st.caption("Handwerkerstunden: 60 € pro Stunde ")
st.caption("Baunebenkosten und Unvorhergesehenes: 10%")